apiVersion: v1
kind: Service
metadata:  
  labels:
    app: sample-html
  name: sample-html-np
  namespace: default
spec:
  ports:
  - port: 80
    nodePort: 31080
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-html
  type: NodePort
