apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-html
  name: sample-html
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-html
  type: LoadBalancer
